name: my_songbook
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version: 1.5.1-alpha+104
version: 1.6.0+107

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.2
  path:
  # share:
  get: ^4.6.5
  sqflite: any
  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  flutter_chord: ^0.1.2
  package_info_plus: any
  intl: any
  hive: any
  file_picker: 8.1.4
  uuid: ^4.5.1
  path_provider: any
  permission_handler: ^11.3.1
  dio:
  # flutter_rustore_update: ^7.0.0
  appmetrica_plugin: ^3.1.0
  # flutter_rustore_review: ^7.0.0
  flutter_native_splash: ^2.3.2
  url_launcher: ^6.1.12
  provider: any
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.1.0
  share_plus: ^10.1.2
  flutter_email_sender: ^6.0.2
  restart_app: ^1.2.1
  cached_network_image: ^3.3.0
  firebase_core: ^3.8.0
  firebase_remote_config: ^5.1.5
  smooth_page_indicator: ^1.1.0
  flutter_markdown: ^0.7.4+3
  # huawei_in_app_update: ^1.2.1
  carousel_slider_plus: ^7.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_keyboard_visibility: ^6.0.0
  archive: ^3.6.1
  flutter_svg: ^2.0.16
  device_info_plus: ^11.2.0
  translit: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^2.0.2
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon_.jpg
  image_path_ios: assets/icon/icon_.jpg
  image_path_android: assets/icon/icon_.jpg
  remove_alpha_ios: true
  min_sdk_android: 23
  adaptive_icon_background: assets/back_icon.png
  adaptive_icon_foreground: assets/icon/adaptive_icon.png
  # adaptive_icon_padding: true

flutter_native_splash:
  image: "assets/guitar.png"
  background_image: "assets/background1.png"
  # color: "#C183FF"
  fullscreen: true
  android: true
  ios: true

  # color_dark: "#121212"

  android_12:
    image: "assets/guitar_for_10.png"
    background_image: "assets/background1.png"
    fullscreen: true
    # color: "#C183FF"
    # icon_background_color: "#ffffff"
    # icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/other/light/
    - assets/other/dark/
    - assets/icon/
    - assets/
    - .env
    - assets/dataJson/news.json
