// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf6lJyavolMiyPHs43W5-Es_OvCz56a0E',
    appId: '1:498046852468:web:1f8c77e7e2b7e461be6021',
    messagingSenderId: '498046852468',
    projectId: 'my-songbook-5fb9f',
    authDomain: 'my-songbook-5fb9f.firebaseapp.com',
    storageBucket: 'my-songbook-5fb9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJSNW11-4ot5WHkmV4pgjjchODSHGn3zs',
    appId: '1:498046852468:android:380172308733ea7cbe6021',
    messagingSenderId: '498046852468',
    projectId: 'my-songbook-5fb9f',
    storageBucket: 'my-songbook-5fb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBrWlKApAQ6ncJzVvrfCZUonp35orw4-0',
    appId: '1:498046852468:ios:53a28e22ddf50b8cbe6021',
    messagingSenderId: '498046852468',
    projectId: 'my-songbook-5fb9f',
    storageBucket: 'my-songbook-5fb9f.appspot.com',
    iosBundleId: 'ru.rudeveloper.mySongbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBrWlKApAQ6ncJzVvrfCZUonp35orw4-0',
    appId: '1:498046852468:ios:6d1e15fd4a7f1a4dbe6021',
    messagingSenderId: '498046852468',
    projectId: 'my-songbook-5fb9f',
    storageBucket: 'my-songbook-5fb9f.appspot.com',
    iosBundleId: 'ru.rudeveloper.mySongbook.RunnerTests',
  );
}
